CREATE DATABASE IF NOT EXISTS disabilitymanager;
USE disabilitymanager;
SELECT PASSWORD('admin123');
CREATE USER 'admin'@'%' IDENTIFIED BY PASSWORD '*01A6717B58FF5C7EAFFF6CB7C96F7428EA65FE4C';
--SET PASSWORD FOR 'admin'@'%' = PASSWORD('admin123');
GRANT ALL PRIVILEGES ON disabilitymanager.* TO 'admin'@'%' WITH GRANT OPTION;
