server:
  contextPath: /
rest:
  base:
    path: /rest/v1
security:
  basic:
    enabled: true
liquibase:
  change-log: "classpath:/db/changelog/change-log-1.0.xml"

spring:
  session:
    store-type: hash_map
  output:
    ansi:
      enabled: always
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8090

---

spring:
  profiles: prod
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:mariadb://localhost:3306/disabilitymanager
    username: admin
    password: admin123
    driver-class-name: org.mariadb.jdbc.Driver
server:
  contextPath: /disability-manager-ws
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: disability123
    key-store-type: PKCS12
    key-alias: disability-manager
    enabled: true

---

spring:
  profiles: test
security:
  basic:
    enabled: false
