server:
  contextPath: /
rest:
  base:
    path: /rest/v1
security:
  basic:
    enabled: true
liquibase:
  change-log: "classpath:/db/changelog/change-log-1.0.xml"

spring:
  session:
    store-type: hash_map
  output:
    ansi:
      enabled: always
  profiles:
    active: prod

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8090

---

spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: disability123
    key-store-type: PKCS12
    key-alias: disability-manager
    enabled: true
