const constants = {
  LOAD_PATIENT_LIST: 'LOAD_PATIENT_LIST',
  LOAD_PATIENT_LIST_SUCCESS: 'LOAD_PATIENT_LIST_SUCCESS',
  LOAD_PATIENT_LIST_ERROR: 'LOAD_PATIENT_LIST_ERROR',
  SAVE_PATIENT: 'SAVE_PATIENT',
  SAVE_PATIENT_SUCCESS: 'SAVE_PATIENT_SUCCESS',
  SAVE_PATIENT_ERROR: 'SAVE_PATIENT_ERROR',
  PRINT_PATIENT: 'PRINT_PATIENT',
  PRINT_PATIENT_SUCCESS: 'PRINT_PATIENT_SUCCESS',
  SAVE_DISABILITY: 'SAVE_DISABILITY',
  SAVE_DISABILITY_SUCCESS: 'SAVE_DISABILITY_SUCCESS',
  SAVE_DISABILITY_ERROR: 'SAVE_DISABILITY_ERROR',
  SAVE_DISABILITY_TMP: 'SAVE_DISABILITY_TMP',
  SAVE_DISABILITY_TMP_SUCCESS: 'SAVE_DISABILITY_TMP_SUCCESS',
  SAVE_DISABILITY_TMP_ERROR: 'SAVE_DISABILITY_TMP_ERROR',
  LOAD_DISABILITY_TMP: 'LOAD_DISABILITY_TMP',
  LOAD_DISABILITY_TMP_SUCCESS: 'LOAD_DISABILITY_SUCCESS',
  LOAD_DISABILITY_TMP_ERROR: 'LOAD_DISABILITY_ERROR',
  LOGIN: 'LOGIN'
};

export default constants;