const constants = {
  LOAD_PATIENT_LIST: 'LOAD_PATIENT_LIST',
  LOAD_PATIENT_LIST_SUCCESS: 'LOAD_PATIENT_LIST_SUCCESS',
  LOAD_PATIENT_LIST_ERROR: 'LOAD_PATIENT_LIST_ERROR',
  SAVE_PATIENT: 'SAVE_PATIENT',
  SAVE_PATIENT_SUCCESS: 'SAVE_PATIENT_SUCCESS',
  SAVE_PATIENT_ERROR: 'SAVE_PATIENT_ERROR',
  PRINT_PATIENT: 'PRINT_PATIENT',
  PRINT_PATIENT_SUCCESS: 'PRINT_PATIENT_SUCCESS',
  LOGIN: 'LOGIN'
};

export default constants;