server:
  contextPath: /form
rest:
  base:
    path: rest/v1
security:
  jwt:
    login:
      url: "auth/login"
    session:
      timeout: 3600000
    secret:
      key: SecretKeyToGenJWTs
  basic:
    enabled: false
liquibase:
  change-log: "classpath:/db/changelog/change-log-1.0.xml"

spring:
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8090


