server:
  contextPath: /form
rest:
  base:
    path: /rest/v1
security:
  basic:
    enabled: true
liquibase:
  change-log: "classpath:/db/changelog/change-log-1.0.xml"

spring:
  session:
    store-type: hash_map
  output:
    ansi:
      enabled: always
  profiles:
    active: dev

---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
#    url: jdbc:h2:file:~/test
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
server:
  port: 8090


